-- Goals: the commitment, and the four family evaluators that measure it.
--
-- `docs/goals.md` is the product spec and `docs/goal-target-architecture.md` the
-- mechanism. Scope resolution lives one file up in `goal_scope.sql` and is the
-- ONLY way any query here decides what is in scope (§8).
--
-- The shape of this file follows from one rule in §8: a goals list costs one
-- round trip per FAMILY, not per goal. So there is no `goal_progress(goal_id)`.
-- Each function below takes a JSON array of requests — already deduped by the
-- client on (family, scope, …) — and returns one row per request, keyed by its
-- index in the array. A list with eight goals over three scopes is four calls.
--
-- Every function is `security invoker` and reads the caller's own rows through
-- RLS. None of them is `security definer`: that would expose every user's
-- submissions through a report, exactly as `progress_analytics.sql` warns.

-- ---------------------------------------------------------------------------
-- The commitment
-- ---------------------------------------------------------------------------

create table public.goals (
  id          bigint generated by default as identity primary key,
  user_id     uuid   references public.profiles(id) on delete cascade not null,
  title       text   not null,
  -- A GoalScope — structurally the practice Track (§3), which is what makes
  -- "practice what remains" free: the scope is handed to the trainer unchanged.
  scope       jsonb  not null default '{}'::jsonb,
  -- A GoalTargetData discriminated union (architecture doc §4).
  target      jsonb  not null,
  -- An explicit presentation choice, not another target or lifecycle. When it
  -- is absent the client derives a stable fallback from active goals.
  is_primary  boolean not null default false,
  -- A horizon, never a second completion condition (§7). Passing it does not
  -- fail the goal, erase progress, or block later achievement.
  deadline    date,
  -- Achievement is sticky: stamped the first time the finish line is met and
  -- never cleared by later catalog drift or a form dip (§7). Status is derived
  -- from these two columns; there is deliberately no mutable `status` column.
  achieved_at timestamp with time zone,
  archived_at timestamp with time zone,
  created_at  timestamp with time zone not null default now(),
  updated_at  timestamp with time zone not null default now(),

  constraint goals_title_length check (length(title) between 1 and 120),
  constraint goals_scope_is_object check (jsonb_typeof(scope) = 'object'),
  -- Structural only, on purpose. §9 wants a new target type to need no
  -- migration, and enumerating the discriminator here would break that promise
  -- for the sake of a check the threat model does not need: RLS already limits
  -- writes to the goal's owner, so the only thing a hand-rolled PATCH can
  -- corrupt is that user's own goal. The defence that matters is the reader's
  -- (architecture doc §7): an unknown `type` must render as an unreadable goal,
  -- never a thrown page. Field-level shape validation lives in `validate` on
  -- the write path.
  constraint goals_target_is_tagged_object check (
    jsonb_typeof(target) = 'object'
    and target ? 'type'
    and jsonb_typeof(target -> 'type') = 'string'
  )
);

-- The list query: a user's active goals, newest first. Archived rows stay
-- readable but are no longer promoted (§7), so they are excluded here rather
-- than deleted.
create index goals_user_idx on public.goals(user_id, archived_at, created_at desc);
-- One explicit main destination per student. Achieved and archived goals are
-- no longer eligible, so their historical flag cannot block a new selection.
create unique index goals_one_active_primary_per_user_idx
  on public.goals (user_id)
  where is_primary and achieved_at is null and archived_at is null;

alter table public.goals enable row level security;

create policy "Users can view their own goals."
  on public.goals for select
  to authenticated
  using ( auth.uid() = user_id );

create policy "Users can insert their own goals."
  on public.goals for insert
  to authenticated
  with check ( auth.uid() = user_id );

create policy "Users can update their own goals."
  on public.goals for update
  to authenticated
  using ( auth.uid() = user_id )
  with check ( auth.uid() = user_id );

create policy "Users can delete their own goals."
  on public.goals for delete
  to authenticated
  using ( auth.uid() = user_id );

-- Column-level update grant, mirroring practice_sessions: everything a student
-- can legitimately change is here, and `user_id`/`created_at` are not, so a
-- goal can never be reassigned or backdated even by a hand-rolled request.
--
-- `achieved_at` IS client-writable. The alternative — a security-definer RPC
-- that re-evaluates and stamps — would require a second implementation of every
-- evaluator in SQL, and the only thing it would prevent is a student lying to
-- themselves about their own private goal (`docs/goals.md` §11, settled
-- 2026-08-10). The client stamps it with `... where achieved_at is null`, which
-- makes the write idempotent and first-writer-wins across tabs.
grant select, insert, delete on public.goals to authenticated;
grant update (title, scope, target, deadline, achieved_at, archived_at, updated_at)
  on public.goals to authenticated;
grant all on public.goals to service_role;

-- Selecting a main goal is one operation, rather than two client PATCHes that
-- could race across tabs. The function is deliberately narrow: a student can
-- only select one of their own active goals.
create or replace function public.set_primary_goal(p_goal_id bigint)
returns public.goals
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected public.goals;
begin
  update public.goals
     set is_primary = false
   where user_id = auth.uid()
     and is_primary
     and id <> p_goal_id;

  update public.goals
     set is_primary = true
   where id = p_goal_id
     and user_id = auth.uid()
     and achieved_at is null
     and archived_at is null
  returning * into selected;

  if not found then
    raise exception 'An active goal is required to become your main goal.';
  end if;

  return selected;
end;
$$;

grant execute on function public.set_primary_goal(bigint) to authenticated;

create or replace function public.handle_goal_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  -- A completed or archived commitment cannot retain the main-goal choice.
  -- This lives in the trigger so ordinary lifecycle updates do not need a
  -- client grant on the presentation-state column.
  if new.achieved_at is not null or new.archived_at is not null then
    new.is_primary = false;
  end if;
  new.updated_at = now();
  return new;
end;
$$;

create or replace trigger update_goals_before_modify
  before update on public.goals
  for each row
  execute function public.handle_goal_update();

-- ---------------------------------------------------------------------------
-- Family evaluators
-- ---------------------------------------------------------------------------
--
-- Shared conventions:
--
--   * `p_requests` is a JSON array; `idx` is the caller's 0-based position in
--     it, so a client can zip results back onto requests without echoing keys;
--   * every request is joined with LEFT JOIN LATERAL … ON TRUE, so a scope that
--     matches nothing still returns its row (zeros) instead of vanishing — a
--     missing row would silently shift every later index;
--   * scope always resolves through `goal_scope_canonicals`, once per request.
--     Resolving it twice in one function would double a full catalog scan;
--   * counts come back raw (numerator and denominator, sample and total), never
--     as ratios. Division stays in TypeScript, where `insufficient_data` is
--     decided — the same split `progress_breakdown` already uses.
--
-- "Graded" means `not skipped and is_correct is not null` throughout: exactly
-- what `times_reviewed` counts, so the set and event families agree on what an
-- attempt is (`docs/attempt-concepts.md`).

-- Set family: `attempted_*` and `solved_*` (§6).
--
-- Requests: [{ "scope": GoalScope }]
--
-- `eligible_total` is the denominator, so this is the one family that filters on
-- gradeability (§4) — an answerless stub must not make 100% unreachable. The
-- numerators are counted over the same eligible set, which is what keeps
-- coverage from ever exceeding 100%.
create or replace function public.goal_set_progress(p_requests jsonb)
returns table (
  idx            integer,
  attempted      bigint,
  solved         bigint,
  eligible_total bigint
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    (r.ord - 1)::integer,
    pg_catalog.count(*) filter (
      where g.gradeable and coalesce(pp.times_reviewed, 0) > 0),
    pg_catalog.count(*) filter (
      where g.gradeable and coalesce(pp.solved, false)),
    pg_catalog.count(g.canonical_id) filter (where g.gradeable)
  from pg_catalog.jsonb_array_elements(p_requests) with ordinality as r(req, ord)
  left join lateral public.goal_scope_canonicals(r.req -> 'scope') g on true
  -- Progress is keyed on the canonical (submissions are canonicalized on
  -- insert), which is exactly what the resolver returns, so this join needs no
  -- coalesce and an alias can never contribute a second row.
  left join public.problem_progress pp
    on pp.problem_id = g.canonical_id and pp.user_id = (select auth.uid())
  group by r.ord
  order by r.ord;
$$;

-- Window family: `accuracy` and `speed` (§6).
--
-- Requests: [{ "scope": GoalScope, "sampleSize": int }]
--
-- Three windows over the same in-scope submissions, because the two targets
-- slice recency differently and a speed goal needs both its own window and an
-- accuracy floor:
--
--   * fresh_*  — the most recent N attempts with `graded_seq = 1`. The
--                fresh-problem rule: without it, re-attempting known problems
--                inflates accuracy until the goal completes itself (§6).
--   * graded_* — the most recent N graded attempts, whatever their history.
--                This is what a speed target's `minAccuracy` floor is measured
--                over: speed is a fluency goal on familiar material, so holding
--                it to first-encounters only would be the wrong denominator.
--   * timed_*  — the most recent N CORRECT graded attempts with a recorded
--                time, summed. Mean is `timed_total_ms / timed_sample` in the
--                evaluator; measuring time over wrong answers would reward
--                guessing, which is the whole reason the floor exists.
--
-- Computing all three costs one scope resolution and one pass; splitting them
-- across requests would cost three.
create or replace function public.goal_window_progress(p_requests jsonb)
returns table (
  idx            integer,
  fresh_sample   bigint,
  fresh_correct  bigint,
  graded_sample  bigint,
  graded_correct bigint,
  timed_sample   bigint,
  timed_total_ms numeric
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    (r.ord - 1)::integer,
    coalesce(w.fresh_sample, 0),
    coalesce(w.fresh_correct, 0),
    coalesce(w.graded_sample, 0),
    coalesce(w.graded_correct, 0),
    coalesce(w.timed_sample, 0),
    coalesce(w.timed_total_ms, 0)
  from pg_catalog.jsonb_array_elements(p_requests) with ordinality as r(req, ord)
  left join lateral (
    with base as (
      select f.is_correct, f.skipped, f.graded_seq, f.elapsed_ms,
             f.created_at, f.submission_id
      from public.submission_facts f
      -- `submission_facts.problem_id` is already canonical, and the resolver
      -- returns canonicals, so this join is the §5 semi-join in effect: work on
      -- a duplicated problem is found through ANY placement in scope, not only
      -- through whichever test its canonical happens to live under.
      join public.goal_scope_canonicals(r.req -> 'scope') g
        on g.canonical_id = f.problem_id
    ),
    fresh as (
      select b.is_correct from base b
      where b.graded_seq = 1
      order by b.created_at desc, b.submission_id desc
      limit (r.req ->> 'sampleSize')::integer
    ),
    graded as (
      select b.is_correct from base b
      where not b.skipped and b.is_correct is not null
      order by b.created_at desc, b.submission_id desc
      limit (r.req ->> 'sampleSize')::integer
    ),
    timed as (
      select b.elapsed_ms from base b
      where not b.skipped and b.is_correct and b.elapsed_ms is not null
      order by b.created_at desc, b.submission_id desc
      limit (r.req ->> 'sampleSize')::integer
    )
    select
      (select pg_catalog.count(*) from fresh)                            as fresh_sample,
      (select pg_catalog.count(*) filter (where fresh.is_correct)
         from fresh)                                                     as fresh_correct,
      (select pg_catalog.count(*) from graded)                           as graded_sample,
      (select pg_catalog.count(*) filter (where graded.is_correct)
         from graded)                                                    as graded_correct,
      (select pg_catalog.count(*) from timed)                            as timed_sample,
      (select coalesce(pg_catalog.sum(timed.elapsed_ms), 0) from timed)   as timed_total_ms
  ) w on true
  order by r.ord;
$$;

-- Accumulation family: `volume` (§6).
--
-- Requests: [{ "scope": GoalScope, "from": timestamptz|null, "to": timestamptz|null }]
--
-- The period's calendar arithmetic is deliberately NOT here: rolling windows,
-- calendar weeks/months and since-creation all reduce to a half-open range, and
-- TypeScript already owns the timezone the goal was created in. SQL counts;
-- the client decides what "this month" means.
--
-- Repeats count — that is the point of a volume goal (§6), so this counts
-- submissions and not distinct problems.
create or replace function public.goal_volume_progress(p_requests jsonb)
returns table (idx integer, graded_submissions bigint)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    (r.ord - 1)::integer,
    coalesce(v.graded_submissions, 0)
  from pg_catalog.jsonb_array_elements(p_requests) with ordinality as r(req, ord)
  left join lateral (
    select pg_catalog.count(*) as graded_submissions
    from public.submission_facts f
    join public.goal_scope_canonicals(r.req -> 'scope') g
      on g.canonical_id = f.problem_id
    where not f.skipped
      and f.is_correct is not null
      and (r.req ->> 'from' is null or f.created_at >= (r.req ->> 'from')::timestamptz)
      and (r.req ->> 'to'   is null or f.created_at <  (r.req ->> 'to')::timestamptz)
  ) v on true
  order by r.ord;
$$;

-- Period family: `streak` (§6).
--
-- Requests: [{ "scope": GoalScope, "timeZone": text, "perDay": int }]
--
-- Days are bucketed with `(created_at at time zone tz)::date`, the same
-- convention `progress_breakdown` uses — reused exactly, not re-derived, so one
-- student's day means one thing across the app. The timezone comes from the
-- goal, never the device: otherwise the same streak breaks or survives
-- depending on where the app is opened.
--
-- The streak counts back from TODAY if today already qualifies, otherwise from
-- yesterday — a day still in progress must not break a streak that is merely
-- unfinished. `today_count` comes back alongside so the UI can say how many
-- more problems keep it alive without a second query.
create or replace function public.goal_streak_progress(p_requests jsonb)
returns table (idx integer, streak_days bigint, today_count bigint)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    (r.ord - 1)::integer,
    coalesce(s.streak_days, 0),
    coalesce(s.today_count, 0)
  from pg_catalog.jsonb_array_elements(p_requests) with ordinality as r(req, ord)
  left join lateral (
    with tz as (
      -- An unknown zone name would raise and take the whole goals list with it,
      -- so fall back rather than trust the stored string.
      select case
        when exists (
          select 1 from pg_catalog.pg_timezone_names z
          where z.name = (r.req ->> 'timeZone')
        ) then (r.req ->> 'timeZone')
        else 'UTC'
      end as name
    ),
    days as (
      select ((f.created_at at time zone (select name from tz))::date) as d,
             pg_catalog.count(*) as n
      from public.submission_facts f
      join public.goal_scope_canonicals(r.req -> 'scope') g
        on g.canonical_id = f.problem_id
      where not f.skipped and f.is_correct is not null
      group by 1
    ),
    today as (
      select ((pg_catalog.now() at time zone (select name from tz))::date) as d
    ),
    qualifying as (
      select days.d from days
      where days.n >= greatest(coalesce((r.req ->> 'perDay')::integer, 1), 1)
    ),
    anchor as (
      select case
        when exists (select 1 from qualifying q, today t where q.d = t.d)
          then (select t.d from today t)
        when exists (select 1 from qualifying q, today t where q.d = t.d - 1)
          then (select t.d from today t) - 1
      end as d
    ),
    -- Gaps and islands: rank qualifying days newest-first from the anchor. A
    -- day is part of the current run exactly when its rank matches its distance
    -- from the anchor; once a gap appears, every later day falls permanently
    -- behind, so counting matches counts the contiguous prefix and nothing else.
    ranked as (
      select q.d, pg_catalog.row_number() over (order by q.d desc) as rn
      from qualifying q, anchor a
      where a.d is not null and q.d <= a.d
    )
    select
      (select pg_catalog.count(*)
         from ranked, anchor a
         where ranked.d = a.d - (ranked.rn - 1)::integer) as streak_days,
      (select coalesce(pg_catalog.max(days.n), 0)
         from days, today t where days.d = t.d)          as today_count
  ) s on true
  order by r.ord;
$$;

grant execute on function public.goal_set_progress(jsonb)    to authenticated;
grant execute on function public.goal_window_progress(jsonb) to authenticated;
grant execute on function public.goal_volume_progress(jsonb) to authenticated;
grant execute on function public.goal_streak_progress(jsonb) to authenticated;
