-- Normalized contest identity: series -> tests
-- production_problems is a denormalized snapshot built from these (plus problem content).

-- A contest series (e.g. "AMC 10", "Putnam").
create table public.series (
  id          bigint generated by default as identity primary key,
  name        text not null unique,
  aops_id     integer default -1,
  is_official boolean not null default false
);

-- A specific test within a series (e.g. "AMC 10A 2024").
create table public.tests (
  id               bigint generated by default as identity primary key,
  series_id        bigint references public.series(id) on delete cascade,
  name             text not null,
  year             integer,
  aops_category_id text,
  section          integer not null default -1,
  -- what type, ie "AIME (which encompass, AIME and all it's user mocks, etc)"
  type             text,
  -- Optional normalized hierarchy metadata for series-review grouping.
  -- Division captures the competition stage (School / Regionals / State /
  -- Nationals); format captures the paper type (Sprint / Target / Team).
  division         text,
  division_order   smallint,
  format           text,
  format_order     smallint,

  is_computational boolean not null default false,
  -- Source-backed test declaration from the scraper. `known` is deliberately
  -- absent here: it is derived per problem from the presence of an answer.
  response_kind    text check (response_kind in
                       ('mcq', 'short_answer', 'proof', 'construction',
                        'estimation', 'interactive', 'unknown')),
  answer_status    text check (answer_status in
                       ('source_missing', 'not_applicable', 'needs_review')),
  difficulty       integer default 0,
  quality          integer default 0,
  -- Default time allotment for taking this test, in seconds. null = untimed /
  -- unlimited. Seeds the time-limit control when a Test-mode session is created.
  time_limit_seconds    integer,
  has_all_answers       boolean not null default false,
  missing_answers_count integer not null default 0,

  -- Stable, source-agnostic identity used by the content-sync merge (see
  -- content_sync.sql). Computed by the scraper and never derived from the
  -- volatile row id, so a test's cloud id stays put across every sync. Nullable
  -- only during the one-time backfill of legacy rows.
  sync_key         text,

  unique(aops_category_id, section)
);

create index tests_series_id_idx on public.tests(series_id);
create unique index tests_sync_key_idx on public.tests(sync_key);

-- Denormalized, "built" problem rows for browsing/practice.
create table public.problems (
  id                 bigint generated by default as identity primary key,

  -- relational link back to the source test
  test_id            bigint references public.tests(id) on delete cascade,
  -- Position within the test, 0-BASED: problem #1 stores n = 0. Every user-facing
  -- render is `n + 1`; only raw-column displays (the problem-details popover) show it
  -- as stored.
  n                  integer not null,

  -- Duplicate pointer. When this row is an ALIAS of another problem (the same
  -- real-world problem placed under a different test, e.g. AMC 10A #18 also
  -- appears as AMC 12A #12), canonical_id points at the CANONICAL problem that
  -- owns the shared state. NULL means this row is its own canonical. Rating
  -- (problem_ratings) and per-user progress (problem_progress) are keyed on the
  -- canonical: submissions are canonicalized on insert (see submissions.sql) and
  -- the read views resolve through coalesce(canonical_id, id). Scraper-owned:
  -- set every sync from the staged canonical_sync_key (content_sync.sql).
  canonical_id       bigint references public.problems(id) on delete set null,

  -- content
  statement          text,                  -- statement parts
  choices            text[],                  -- choice texts; null if not MCQ
  answer_index       integer default -1,      -- 0-based index into choices; -1 = unknown
  official_solutions text[],                  -- official solution content strings; null if none

  -- metadata
  aops_id            int default null,
  topic              text,
  tags               text[],                  -- tags
  is_computational   boolean not null default false,
  -- Resolved per-problem coverage from the scraper: problem override, then
  -- test declaration, then `known` when a usable answer exists.
  response_kind      text check (response_kind in
                         ('mcq', 'short_answer', 'proof', 'construction',
                          'estimation', 'interactive', 'unknown')),
  answer_status      text check (answer_status in
                         ('known', 'source_missing', 'not_applicable', 'needs_review')),
  difficulty         integer default 0,
  quality            integer default 0,
  verified           boolean not null default false,
  notes              text,

  built_at           timestamp with time zone not null default now(),

  -- Stable, source-agnostic identity used by the content-sync merge (see
  -- content_sync.sql): the parent test's sync_key plus this problem's n. Keeps
  -- the cloud id (and every submissions/feedback FK pointing at it) fixed across
  -- syncs. Nullable only during the one-time backfill of legacy rows.
  sync_key           text,

  unique (test_id, n)
);

create index problems_test_id_idx on public.problems(test_id);
create unique index problems_sync_key_idx on public.problems(sync_key);
-- Aliases only; canonicals (the common case) are excluded so the index stays small.
create index problems_canonical_id_idx on public.problems(canonical_id)
  where canonical_id is not null;

-- Enable Row Level Security (RLS)
alter table public.series enable row level security;
alter table public.tests enable row level security;
alter table public.problems enable row level security;

-- RLS Policies: world-readable, writes go through service_role (build pipeline).
create policy "Series are viewable by everyone."
  on public.series for select
  using ( true );

create policy "Tests are viewable by everyone."
  on public.tests for select
  using ( true );

create policy "Problems are viewable by everyone."
  on public.problems for select
  using ( true );

-- Grant permissions for roles
grant select on public.series to anon, authenticated;
grant select on public.tests to anon, authenticated;
grant select on public.problems to anon, authenticated;

grant all on public.series to service_role;
grant all on public.tests to service_role;
grant all on public.problems to service_role;

-- Helper function to recalculate cached answer columns on a test.
create or replace function public.recalculate_test_answers(t_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  graded_total bigint;
  missing_answers bigint;
begin
  select pg_catalog.count(*) into graded_total
  from public.problems
  where test_id = t_id
    and coalesce(answer_status, '') <> 'not_applicable';

  select pg_catalog.count(*) into missing_answers
  from public.problems
  where test_id = t_id
    and coalesce(answer_status, '') <> 'not_applicable'
    and (answer_index = -1 or answer_index is null);

  update public.tests
  set
    has_all_answers = (graded_total > 0 and missing_answers = 0),
    missing_answers_count = missing_answers::integer
  where id = t_id;
end;
$$;

-- Trigger function to handle problem changes.
create or replace function public.handle_problem_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if TG_OP = 'INSERT' or TG_OP = 'UPDATE' then
    if NEW.test_id is not null then
      perform public.recalculate_test_answers(NEW.test_id);
    end if;
  end if;

  if TG_OP = 'DELETE' or TG_OP = 'UPDATE' then
    if OLD.test_id is not null and (TG_OP = 'DELETE' or OLD.test_id != coalesce(NEW.test_id, -1)) then
      perform public.recalculate_test_answers(OLD.test_id);
    end if;
  end if;

  return null;
end;
$$;

-- Trigger on the problems table to automatically update test caches on changes.
create or replace trigger on_problem_changed
  after insert or update or delete on public.problems
  for each row
  execute function public.handle_problem_change();
